### ISSUE TITLE
魔盒前端公共组件

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/jx3box-ui-react#1]
为dps计算器等其它react前端业务线做准备，需要对公共组件生产一个react版本。

首批只移植重要的几个模块
原vue2版本 https://github.com/JX3BOX/jx3box-common-ui

# 全局模块
- [x] #2
- [x] #3
- [x] #5
- [x] #4
- [x] #6

其他cms栏目，会暂时继续沿用vue2，后续持续将vue3模块补齐。
而react项目只涉及应用类型，只移植应用需要用到的模块

**Comment by gaohan1994** [comment]
Fixed all sub issues.
Please code-review @iRuxu

**Comment by gaohan1994** [comment]
Done so close this issue
